# Backend service only
services:
  - type: web
    name: SE401-Design-Pattern-api
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://SE401-Design-Pattern.onrender.com
      - key: GEMINI_API_KEY
        sync: false
