# Backend service only
services:
  - type: web
    name: SE401-Design-Pattern-api
    runtime: node
    buildCommand: npm ci || npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://build-aqaycn8ew-tinhs-projects.vercel.app
      - key: GEMINI_API_KEY
        sync: false
